apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: secure-gitops.k8s.local
spec:
  cloudProvider: aws
  configBase: s3://REPLACE_WITH_KOPS_STATE_BUCKET/secure-gitops.k8s.local
  kubernetesVersion: "1.30.0"
  networking:
    cilium: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - 0.0.0.0/0
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  iam:
    allowContainerRegistry: true
    legacy: false
  etcdClusters:
    - name: main
      members:
        - name: a
          instanceGroup: control-plane
    - name: events
      members:
        - name: a
          instanceGroup: control-plane
  subnets:
    - name: public-a
      type: Public
      zone: eu-west-3a
      cidr: 172.20.32.0/19
  topology:
    dns:
      type: None
    masters: public
    nodes: public
  networkCIDR: 172.20.0.0/16

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: control-plane
  labels:
    kops.k8s.io/cluster: secure-gitops.k8s.local
spec:
  role: ControlPlane
  image: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*
  machineType: t3.small
  minSize: 1
  maxSize: 1
  subnets:
    - public-a

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes
  labels:
    kops.k8s.io/cluster: secure-gitops.k8s.local
spec:
  role: Node
  image: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*
  machineType: t3.small
  minSize: 1
  maxSize: 2
  subnets:
    - public-a

