apiVersion: v1
kind: Namespace
metadata:
  name: taskapp
  labels:
    app.kubernetes.io/part-of: taskapp
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/part-of: gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    app.kubernetes.io/part-of: policy