global:
  environment: prod

serviceAccount:
  create: true
  name: taskapp
  automountServiceAccountToken: false

backend:
  name: taskapp-backend
  replicaCount: 1
  image:
    repository: oparag/taskapp-backend
    tag: "499ab98"
    pullPolicy: IfNotPresent
  env:
    databaseHost: taskapp-postgres.crammy6g8qwh.eu-west-3.rds.amazonaws.com
    databasePort: "5432"
    databaseName: taskapp
    secretName: taskapp-backend-secrets
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  probes:
    path: /api/health
    initialDelaySeconds: 10
    periodSeconds: 10
  metrics:
    enabled: false
    path: /metrics

frontend:
  name: taskapp-frontend
  replicaCount: 1
  image:
    repository: oparag/taskapp-frontend
    tag: "499ab98"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  probes:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

serviceMonitor:
  enabled: false
  interval: 30s
