apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
    app.kubernetes.io/part-of: taskapp
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.frontend.name }}
        app.kubernetes.io/part-of: taskapp
        app.kubernetes.io/component: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
