apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
    app.kubernetes.io/part-of: taskapp
    app.kubernetes.io/component: frontend
{{- with .Values.frontend.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
{{- with .Values.frontend.service.tls }}
{{- if .enabled }}
    - name: https
      port: {{ .port }}
      targetPort: http
{{- end }}
{{- end }}
