{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/part-of: taskapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.backend.name }}
  endpoints:
    - port: http
      path: {{ .Values.backend.metrics.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}

