apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: taskapp
    app.kubernetes.io/part-of: taskapp
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
