apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp
  namespace: argocd
  labels:
    app.kubernetes.io/name: taskapp
    app.kubernetes.io/part-of: taskapp
spec:
  project: default

  source:
    repoURL: https://github.com/oparag-dev/secure-gitops-k8s-delivery.git
    targetRevision: HEAD
    path: helm/taskapp
    helm:
      releaseName: taskapp

  destination:
    server: https://kubernetes.default.svc
    namespace: taskapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
